import asyncio

from sqlmodel import select

from app.db.init_db import create_db_and_tables
from app.db.session import session_factory
from app.models.item import Item


GAMES = [
    {
        "titre": "The Legend of Zelda: Breath of the Wild",
        "categorie": "Aventure",
        "description": "Une aventure en monde ouvert au royaume d'Hyrule.",
        "image_url": "https://placehold.co/600x800?text=Zelda+BOTW",
        "annee": 2017,
        "studio": "Nintendo",
        "plateforme": "Nintendo Switch",
    },
    {
        "titre": "Hollow Knight",
        "categorie": "Action",
        "description": "Une exploration exigeante dans le royaume de Hallownest.",
        "image_url": "https://placehold.co/600x800?text=Hollow+Knight",
        "annee": 2017,
        "studio": "Team Cherry",
        "plateforme": "PC",
    },
    {
        "titre": "Celeste",
        "categorie": "Plateforme",
        "description": "Une ascension precise et emouvante du mont Celeste.",
        "image_url": "https://placehold.co/600x800?text=Celeste",
        "annee": 2018,
        "studio": "Maddy Makes Games",
        "plateforme": "PC",
    },
    {
        "titre": "Hades",
        "categorie": "Action",
        "description": "Une fuite des enfers rythmee par des combats rapides.",
        "image_url": "https://placehold.co/600x800?text=Hades",
        "annee": 2020,
        "studio": "Supergiant Games",
        "plateforme": "PC",
    },
    {
        "titre": "Stardew Valley",
        "categorie": "Simulation",
        "description": "Une simulation de ferme et de vie dans une petite ville.",
        "image_url": "https://placehold.co/600x800?text=Stardew+Valley",
        "annee": 2016,
        "studio": "ConcernedApe",
        "plateforme": "PC",
    },
    {
        "titre": "Portal 2",
        "categorie": "Reflexion",
        "description": "Des enigmes basees sur des portails et la physique.",
        "image_url": "https://placehold.co/600x800?text=Portal+2",
        "annee": 2011,
        "studio": "Valve",
        "plateforme": "PC",
    },
    {
        "titre": "The Witcher 3: Wild Hunt",
        "categorie": "RPG",
        "description": "Une quete epique dans un monde fantastique ouvert.",
        "image_url": "https://placehold.co/600x800?text=The+Witcher+3",
        "annee": 2015,
        "studio": "CD Projekt Red",
        "plateforme": "PC",
    },
    {
        "titre": "Minecraft",
        "categorie": "Sandbox",
        "description": "Un monde de blocs a explorer, construire et transformer.",
        "image_url": "https://placehold.co/600x800?text=Minecraft",
        "annee": 2011,
        "studio": "Mojang Studios",
        "plateforme": "Multi-plateforme",
    },
    {
        "titre": "Mario Kart 8 Deluxe",
        "categorie": "Course",
        "description": "Des courses rapides dans l'univers de Mario.",
        "image_url": "https://placehold.co/600x800?text=Mario+Kart+8",
        "annee": 2017,
        "studio": "Nintendo",
        "plateforme": "Nintendo Switch",
    },
    {
        "titre": "Sid Meier's Civilization VI",
        "categorie": "Strategie",
        "description": "Construire une civilisation de l'Antiquite au futur.",
        "image_url": "https://placehold.co/600x800?text=Civilization+VI",
        "annee": 2016,
        "studio": "Firaxis Games",
        "plateforme": "PC",
    },
    {
        "titre": "Elden Ring",
        "categorie": "RPG",
        "description": "Un vaste monde sombre rempli de combats exigeants.",
        "image_url": "https://placehold.co/600x800?text=Elden+Ring",
        "annee": 2022,
        "studio": "FromSoftware",
        "plateforme": "PC",
    },
    {
        "titre": "God of War",
        "categorie": "Action",
        "description": "Le voyage de Kratos et Atreus dans les royaumes nordiques.",
        "image_url": "https://placehold.co/600x800?text=God+of+War",
        "annee": 2018,
        "studio": "Santa Monica Studio",
        "plateforme": "PlayStation 4",
    },
    {
        "titre": "Red Dead Redemption 2",
        "categorie": "Aventure",
        "description": "La fin de l'epoque des hors-la-loi dans l'Ouest americain.",
        "image_url": "https://placehold.co/600x800?text=Red+Dead+2",
        "annee": 2018,
        "studio": "Rockstar Games",
        "plateforme": "PlayStation 4",
    },
    {
        "titre": "Animal Crossing: New Horizons",
        "categorie": "Simulation",
        "description": "Amenager une ile et partager la vie de ses habitants.",
        "image_url": "https://placehold.co/600x800?text=Animal+Crossing",
        "annee": 2020,
        "studio": "Nintendo",
        "plateforme": "Nintendo Switch",
    },
    {
        "titre": "Ori and the Will of the Wisps",
        "categorie": "Plateforme",
        "description": "Une aventure poetique dans une foret enchantee.",
        "image_url": "https://placehold.co/600x800?text=Ori",
        "annee": 2020,
        "studio": "Moon Studios",
        "plateforme": "PC",
    },
    {
        "titre": "Disco Elysium",
        "categorie": "RPG",
        "description": "Une enquete narrative fondee sur les dialogues et les choix.",
        "image_url": "https://placehold.co/600x800?text=Disco+Elysium",
        "annee": 2019,
        "studio": "ZA/UM",
        "plateforme": "PC",
    },
    {
        "titre": "Doom Eternal",
        "categorie": "Action",
        "description": "Des combats rapides contre les armees infernales.",
        "image_url": "https://placehold.co/600x800?text=Doom+Eternal",
        "annee": 2020,
        "studio": "id Software",
        "plateforme": "PC",
    },
    {
        "titre": "EA Sports FC 24",
        "categorie": "Sport",
        "description": "Une simulation de football avec clubs et competitions.",
        "image_url": "https://placehold.co/600x800?text=EA+Sports+FC+24",
        "annee": 2023,
        "studio": "EA Sports",
        "plateforme": "PlayStation 5",
    },
    {
        "titre": "Rocket League",
        "categorie": "Sport",
        "description": "Du football joue avec des voitures propulsees.",
        "image_url": "https://placehold.co/600x800?text=Rocket+League",
        "annee": 2015,
        "studio": "Psyonix",
        "plateforme": "Multi-plateforme",
    },
    {
        "titre": "Slay the Spire",
        "categorie": "Strategie",
        "description": "Construire un paquet de cartes pour gravir une tour.",
        "image_url": "https://placehold.co/600x800?text=Slay+the+Spire",
        "annee": 2019,
        "studio": "Mega Crit",
        "plateforme": "PC",
    },
    {
        "titre": "Dead Cells",
        "categorie": "Action",
        "description": "Explorer un chateau changeant avec des combats nerveux.",
        "image_url": "https://placehold.co/600x800?text=Dead+Cells",
        "annee": 2018,
        "studio": "Motion Twin",
        "plateforme": "PC",
    },
    {
        "titre": "Undertale",
        "categorie": "RPG",
        "description": "Un jeu de role ou les ennemis peuvent etre epargnes.",
        "image_url": "https://placehold.co/600x800?text=Undertale",
        "annee": 2015,
        "studio": "Toby Fox",
        "plateforme": "PC",
    },
    {
        "titre": "Overcooked 2",
        "categorie": "Cooperation",
        "description": "Preparer des plats en equipe dans des cuisines chaotiques.",
        "image_url": "https://placehold.co/600x800?text=Overcooked+2",
        "annee": 2018,
        "studio": "Ghost Town Games",
        "plateforme": "Multi-plateforme",
    },
    {
        "titre": "It Takes Two",
        "categorie": "Cooperation",
        "description": "Une aventure entierement concue pour deux joueurs.",
        "image_url": "https://placehold.co/600x800?text=It+Takes+Two",
        "annee": 2021,
        "studio": "Hazelight Studios",
        "plateforme": "PC",
    },
    {
        "titre": "Forza Horizon 5",
        "categorie": "Course",
        "description": "Un festival automobile en monde ouvert au Mexique.",
        "image_url": "https://placehold.co/600x800?text=Forza+Horizon+5",
        "annee": 2021,
        "studio": "Playground Games",
        "plateforme": "Xbox Series",
    },
    {
        "titre": "Gran Turismo 7",
        "categorie": "Course",
        "description": "Une simulation automobile centree sur la collection.",
        "image_url": "https://placehold.co/600x800?text=Gran+Turismo+7",
        "annee": 2022,
        "studio": "Polyphony Digital",
        "plateforme": "PlayStation 5",
    },
    {
        "titre": "Age of Empires IV",
        "categorie": "Strategie",
        "description": "Diriger des civilisations historiques en temps reel.",
        "image_url": "https://placehold.co/600x800?text=Age+of+Empires+IV",
        "annee": 2021,
        "studio": "Relic Entertainment",
        "plateforme": "PC",
    },
    {
        "titre": "Cities: Skylines",
        "categorie": "Simulation",
        "description": "Construire et administrer une ville moderne.",
        "image_url": "https://placehold.co/600x800?text=Cities+Skylines",
        "annee": 2015,
        "studio": "Colossal Order",
        "plateforme": "PC",
    },
    {
        "titre": "Subnautica",
        "categorie": "Aventure",
        "description": "Survivre et explorer les oceans d'une planete inconnue.",
        "image_url": "https://placehold.co/600x800?text=Subnautica",
        "annee": 2018,
        "studio": "Unknown Worlds",
        "plateforme": "PC",
    },
    {
        "titre": "Outer Wilds",
        "categorie": "Aventure",
        "description": "Explorer un systeme solaire prisonnier d'une boucle temporelle.",
        "image_url": "https://placehold.co/600x800?text=Outer+Wilds",
        "annee": 2019,
        "studio": "Mobius Digital",
        "plateforme": "PC",
    },
    {
        "titre": "Mass Effect Legendary Edition",
        "categorie": "RPG",
        "description": "Une trilogie spatiale fondee sur les choix du joueur.",
        "image_url": "https://placehold.co/600x800?text=Mass+Effect",
        "annee": 2021,
        "studio": "BioWare",
        "plateforme": "PC",
    },
    {
        "titre": "The Elder Scrolls V: Skyrim",
        "categorie": "RPG",
        "description": "Explorer librement la province nordique de Bordeciel.",
        "image_url": "https://placehold.co/600x800?text=Skyrim",
        "annee": 2011,
        "studio": "Bethesda Game Studios",
        "plateforme": "PC",
    },
    {
        "titre": "Cuphead",
        "categorie": "Plateforme",
        "description": "Des combats de boss inspires des dessins animes anciens.",
        "image_url": "https://placehold.co/600x800?text=Cuphead",
        "annee": 2017,
        "studio": "Studio MDHR",
        "plateforme": "PC",
    },
    {
        "titre": "Sonic Mania",
        "categorie": "Plateforme",
        "description": "Une aventure rapide inspiree des classiques de Sonic.",
        "image_url": "https://placehold.co/600x800?text=Sonic+Mania",
        "annee": 2017,
        "studio": "Christian Whitehead",
        "plateforme": "Multi-plateforme",
    },
    {
        "titre": "Street Fighter 6",
        "categorie": "Combat",
        "description": "Des affrontements techniques entre combattants du monde entier.",
        "image_url": "https://placehold.co/600x800?text=Street+Fighter+6",
        "annee": 2023,
        "studio": "Capcom",
        "plateforme": "PlayStation 5",
    },
    {
        "titre": "Tekken 8",
        "categorie": "Combat",
        "description": "Un tournoi de combat centre sur la famille Mishima.",
        "image_url": "https://placehold.co/600x800?text=Tekken+8",
        "annee": 2024,
        "studio": "Bandai Namco Studios",
        "plateforme": "PlayStation 5",
    },
    {
        "titre": "Tetris Effect: Connected",
        "categorie": "Reflexion",
        "description": "Le jeu de blocs classique accompagne d'une experience musicale.",
        "image_url": "https://placehold.co/600x800?text=Tetris+Effect",
        "annee": 2020,
        "studio": "Monstars",
        "plateforme": "PC",
    },
    {
        "titre": "Professor Layton and the Curious Village",
        "categorie": "Reflexion",
        "description": "Une enquete composee d'enigmes dans le village de Saint-Mystere.",
        "image_url": "https://placehold.co/600x800?text=Professor+Layton",
        "annee": 2007,
        "studio": "Level-5",
        "plateforme": "Nintendo DS",
    },
    {
        "titre": "League of Legends",
        "categorie": "Strategie",
        "description": "Deux equipes s'affrontent pour detruire la base adverse.",
        "image_url": "https://placehold.co/600x800?text=League+of+Legends",
        "annee": 2009,
        "studio": "Riot Games",
        "plateforme": "PC",
    },
    {
        "titre": "Sea of Thieves",
        "categorie": "Aventure",
        "description": "Une vie de pirate partagee dans un monde ouvert.",
        "image_url": "https://placehold.co/600x800?text=Sea+of+Thieves",
        "annee": 2018,
        "studio": "Rare",
        "plateforme": "Xbox One",
    },
]


async def seed() -> None:
    await create_db_and_tables()

    async with session_factory() as session:
        existing_titles = set(
            (await session.scalars(select(Item.titre))).all(),
        )
        missing_games = [
            Item(**game)
            for game in GAMES
            if game["titre"] not in existing_titles
        ]

        session.add_all(missing_games)
        await session.commit()

        print(f"{len(missing_games)} jeux ajoutes au catalogue")


if __name__ == "__main__":
    asyncio.run(seed())
